# Generated by Django 4.2.6 on 2023-10-10 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_fotografia_data_fotografia_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 22, 51, 14, 112561)),
        ),
    ]
